// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pcmuubmjfejipcfqusnf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjbXV1Ym1qZmVqaXBjZnF1c25mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMjAwMjUsImV4cCI6MjA2Nzg5NjAyNX0.h2sFSuOOvvWGHrOkxtoCBjxAEBpPgJpvmYEJkrDJV6E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});